attempt to cleanup install/mount path to /opt/redpitaya

diff --git a/OS/buildroot/overlay/sbin/bazaar b/OS/buildroot/overlay/sbin/bazaar
--- a/OS/buildroot/overlay/sbin/bazaar
+++ b/OS/buildroot/overlay/sbin/bazaar
@@ -26,8 +26,7 @@ VER=
 OS=ecosystem
 
 # Default target directory for applications
-BASEDIR=/opt/redpitaya
-TARGET=${BASEDIR}/www/apps/
+TARGET=${PATH_REDPITAYA}/www/apps/
 
 # Get parameters or print usage if they are wrong
 [ $# -lt 2 ] && {
@@ -61,7 +60,7 @@ MD5=$4
 
     # Ecosystem special case
     if [ "x${APP}" == "x${OS}" ]; then
-        TARGET=/opt
+        TARGET=${PATH_REDPITAYA}
     fi
 
 
@@ -86,7 +85,7 @@ MD5=$4
         exit 3;
     }
 
-    mount -o rw,remount /opt
+    mount -o rw,remount ${PATH_REDPITAYA}
     status=$?
     [ $status -ne 0 ] && {
         echo "Error mounting SD card RW." 1>&2
@@ -99,20 +98,13 @@ MD5=$4
     [ $status -ne 0 ] && {
         echo "Error extracting archive." 1>&2
         rm -f /tmp/app.zip
-        mount -o ro,remount /opt
+        mount -o ro,remount ${PATH_REDPITAYA}
         exit 4;
     }
 
     rm -f /tmp/app.zip
 
-    # Ecosystem special case - run os-postinstall
-    if [ "x${APP}" == "x${OS}" ]; then
-        if [ -x /opt/sbin/os-postinstall ]; then
-            /opt/sbin/os-postinstall
-        fi
-    fi
-
-    mount -o ro,remount /opt
+    mount -o ro,remount ${PATH_REDPITAYA}
 
     # Ecosystem special case - schedule a reboot
     if [ "x${APP}" == "x${OS}" ]; then
@@ -132,54 +124,54 @@ MD5=$4
     fi
 
     # Applications
-    [ -d /opt/redpitaya/www/apps/${APP} ] || {
-        echo "Trying to remove non-existent /opt/redpitaya/www/apps/${APP}." 1>&2
+    [ -d ${PATH_REDPITAYA}/www/apps/${APP} ] || {
+        echo "Trying to remove non-existent ${PATH_REDPITAYA}/www/apps/${APP}." 1>&2
         exit 0;
     }
 
-    mount -o rw,remount /opt
+    mount -o rw,remount ${PATH_REDPITAYA}
     status=$?
     [ $status -ne 0 ] && {
         echo "Error mounting SD card RW." 1>&2
         exit 4;
     }
 
-    rm -rf /opt/redpitaya/www/apps/${APP}
+    rm -rf ${PATH_REDPITAYA}/www/apps/${APP}
     status=$?
     [ $status -ne 0 ] && {
-        echo "Error rmoving /opt/redpitaya/www/apps/${APP}" 1>&2
+        echo "Error rmoving ${PATH_REDPITAYA}/www/apps/${APP}" 1>&2
         exit 4;
     }
 
-    mount -o ro,remount /opt
+    mount -o ro,remount ${PATH_REDPITAYA}
 
     exit 0;
 }
 
 [ "x${ACTION}" == "xidgen" ] && {
 
-    mount -o rw,remount /opt
+    mount -o rw,remount ${PATH_REDPITAYA}
     status=$?
     [ $status -ne 0 ] && {
         echo "Error mounting SD card RW." 1>&2
         exit 4;
     }
 
-	${BASEDIR}/sbin/idgen -o ${TARGET}/idfile.id
+	${PATH_REDPITAYA}/sbin/idgen -o ${TARGET}/idfile.id
     status=$?
     [ $status -ne 0 ] && {
         echo "Error creating ID-file" 1>&2
         exit 4;
     }
 
-    mount -o ro,remount /opt
+    mount -o ro,remount ${PATH_REDPITAYA}
 
     exit 0;
 }
 
 [ "x${ACTION}" == "xlic" ] && {
 
-    mount -o rw,remount /opt
+    mount -o rw,remount ${PATH_REDPITAYA}
     status=$?
     [ $status -ne 0 ] && {
         echo "Error mounting SD card RW." 1>&2
@@ -193,7 +185,7 @@ MD5=$4
         exit 4;
     }
 
-    mount -o ro,remount /opt
+    mount -o ro,remount ${PATH_REDPITAYA}
 
     exit 0;
 }
